apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Kompose\kompose.exe convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: app
  name: app
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: app


# apiVersion: v1
# kind: Service
# metadata:
#   name: spring-app
# spec:
#   type: LoadBalancer
#   ports:
#     - port: 8080
#       targetPort: 8080
#   selector:
#     app: spring-app
