apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Kompose\kompose.exe convert
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: db
  name: db
spec:
  ports:
    - name: "5433"
      port: 5433
      targetPort: 5432
  selector:
    io.kompose.service: db


# apiVersion: v1
# kind: Service
# metadata:
#   name: db
# spec:
#   type: ClusterIP
#   ports:
#     - port: 5432  # Puerto en el servicio
#       targetPort: 5432  # Puerto en el contenedor PostgreSQL
#   selector:
#     app: db  # Debe coincidir con la etiqueta del Deployment de la BD
